/*
 * Arena.cpp
 *
 *  Created on: Feb 8, 2017
 *      Author: Thomas Boland
 */

#include <Models/Arena.h>

Arena::Arena() {
	// Arena divided into 3'x3' cells
	// Each cell has tags for [nearest] objects
	// Finer movement should be able to be done
	// after major cell movement

	// 288 252 216 180 144 108 72 36 0

	cells = {"A0" = new ArenaCell({-326, -234}, {54, 162}, {"RedNearestLift"   = "B0",
	                                               "BlueNearestLift"  = "A4",
	                                               "RedNearestRope"   = "B0",
	                                               "BlueNearestRope"  = "A3",
	                                               "RedFarStation"    = "A5",
	                                               "BlueFarStation"   = "HERE",
	                                               "RedHomeStation"   = "B0",
	                                               "BlueHomeStation"  = "A5",
	                                               "RedAllianceWall"  = "HERE",
	                                               "BlueAllianceWall" = "A5"}),
	         "A1" = new ArenaCell({-234, -126}, {54, 162}, {"RedNearestLift"   = "HERE",
                                                   "BlueNearestLift"  = "A4",
												   "RedNearestRope"   = "A2",
                                                   "BlueNearestRope"  = "A3",
												   "RedFarStation"    = "A5",
												   "BlueFarStation"   = "A0",
												   "RedHomeStation"   = "A0",
												   "BlueHomeStation"  = "A5",
												   "RedAllianceWall"  = "A0",
												   "BlueAllianceWall" = "A5"}),
	         "A2" = new ArenaCell({-126, -90}, {54, 162}, {"RedNearestLift"   = "A1",
                                                   "BlueNearestLift"  = "A4",
                                                   "RedNearestRope"   = "HERE",
                                                   "BlueNearestRope"  = "A3",
                                    			   "RedFarStation"    = "A5",
												   "BlueFarStation"   = "A0",
												   "RedHomeStation"   = "A0",
												   "BlueHomeStation"  = "A5",
												   "RedAllianceWall"  = "A0",
												   "BlueAllianceWall" = "A5"}),
	         "A3" = new ArenaCell({90,126}, {54, 162}, {"RedNearestLift"   = "A1",
	        		 	 	 	 	 	 	 	   "BlueNearestLift"  = "A4",
												   "RedNearestRope"   = "A2",
												   "BlueNearestRope"  = "HERE",
												   "RedFarStation"    = "A5",
												   "BlueFarStation"   = "A0",
												   "RedHomeStation"   = "A0",
												   "BlueHomeStation"  = "A5",
												   "RedAllianceWall"  = "A0",
												   "BlueAllianceWall" = "A5"}),
	         "A4" = new ArenaCell({126, 234}, {54, 162}, {"RedNearestLift"   = "A1",
												   "BlueNearestLift"  = "HERE",
												   "RedNearestRope"   = "A2",
												   "BlueNearestRope"  = "A3",
												   "RedFarStation"    = "A5",
												   "BlueFarStation"   = "A0",
												   "RedHomeStation"   = "A0",
												   "BlueHomeStation"  = "A5",
												   "RedAllianceWall"  = "A0",
												   "BlueAllianceWall" = "A5"}),
	         "A5" = new ArenaCell({234, 326}, {54, 162}, {"RedNearestLift"   = "A1",
												   "BlueNearestLift"  = "B5",
												   "RedNearestRope"   = "A2",
												   "BlueNearestRope"  = "B5",
												   "RedFarStation"    = "HERE",
												   "BlueFarStation"   = "A0",
												   "RedHomeStation"   = "A0",
												   "BlueHomeStation"  = "B5",
												   "RedAllianceWall"  = "A0",
												   "BlueAllianceWall" = "HERE"}),
			 "B0" = new ArenaCell({-326, -234}, {-54, 54}, {"RedNearestLift"   = "HERE",
												   "BlueNearestLift"  = "C0",
												   "RedNearestRope"   = "HERE",
												   "BlueNearestRope"  = "C0",
												   "RedFarStation"    = "A0",
												   "BlueFarStation"   = "A0",
												   "RedHomeStation"   = "HERE",
												   "BlueHomeStation"  = "A0",
												   "RedAllianceWall"  = "HERE",
												   "BlueAllianceWall" = "A0"}),
	         "B1" = new ArenaCell({-234, -126}, {-54, 54}, {"RedNearestLift"   = "B0",
												   "BlueNearestLift"  = "B0",
												   "RedNearestRope"   = "B0",
												   "BlueNearestRope"  = "B0",
												   "RedFarStation"    = "B0",
												   "BlueFarStation"   = "B0",
												   "RedHomeStation"   = "B0",
												   "BlueHomeStation"  = "B0",
												   "RedAllianceWall"  = "B0",
												   "BlueAllianceWall" = "B0"}),
	         "B2" = new ArenaCell({-126, -90}, {-54, 54}, {"RedNearestLift"   = "C2",
												   "BlueNearestLift"  = "A3",
												   "RedNearestRope"   = "C2",
												   "BlueNearestRope"  = "A3",
												   "RedFarStation"    = "A3",
												   "BlueFarStation"   = "A2",
												   "RedHomeStation"   = "A2",
												   "BlueHomeStation"  = "A3",
												   "RedAllianceWall"  = "A2",
												   "BlueAllianceWall" = "A3"}),
	         "B3" = new ArenaCell({90, 126}, {-54, 54}, {"RedNearestLift"   = "A2",
												   "BlueNearestLift"  = "C3",
												   "RedNearestRope"   = "A2",
												   "BlueNearestRope"  = "C3",
												   "RedFarStation"    = "A3",
												   "BlueFarStation"   = "A2",
												   "RedHomeStation"   = "A2",
												   "BlueHomeStation"  = "A3",
												   "RedAllianceWall"  = "A2",
												   "BlueAllianceWall" = "A3"}),
	         "B4" = new ArenaCell({126, 234}, {-54, 54}, {"RedNearestLift"   = "C5",
												   "BlueNearestLift"  = "C5",
												   "RedNearestRope"   = "C5",
												   "BlueNearestRope"  = "C5",
												   "RedFarStation"    = "C5",
												   "BlueFarStation"   = "C5",
												   "RedHomeStation"   = "C5",
												   "BlueHomeStation"  = "C5",
												   "RedAllianceWall"  = "C5",
												   "BlueAllianceWall" = "C5"}),
	         "B5" = new ArenaCell({234, 326}, {-54, 54}, {"RedNearestLift"   = "C5",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
			 "C0" = new ArenaCell({-326, -234}, {-162, -54}, {"RedNearestLift"   = "B0",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
	         "C1" = new ArenaCell({-234, -126}, {-162, -54}, {"RedNearestLift"   = "C1",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
	         "C2" = new ArenaCell({-126, -90}, {-162, -54}, {"RedNearestLift"   = "C1",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
	         "C3" = new ArenaCell({90, 126}, {-162, -54}, {"RedNearestLift"   = "C1",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
	         "C4" = new ArenaCell({126, 234}, {-162, -54}, {"RedNearestLift"   = "C1",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
	         "C5" = new ArenaCell({234, 326}, {-162, -54}, {"RedNearestLift"   = "C1",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""}),
	         "Z0" = new ArenaCell({-90, 90}, {-162, 162}, {"RedNearestLift"   = "A2",
												   "BlueNearestLift"  = "",
												   "RedNearestRope"   = "",
												   "BlueNearestRope"  = "",
												   "RedFarStation"    = "",
												   "BlueFarStation"   = "",
												   "RedHomeStation"   = "",
												   "BlueHomeStation"  = "",
												   "RedAllianceWall"  = "",
												   "BlueAllianceWall" = ""})
	        };
}

std::string Arena::GetCell(Position pos) {
	// Loop through all cells until one is found where pos is inside bounds
	return "";
}

Position Arena::GetCellTarget(std::string cell) {
	return cells[cell].GetTarget();
}

std::string Arena::GetTag(std::string cell, std::string key) {
	return cells[cell].GetTag(key);
}
