/*
 * Arena.cpp
 *
 *  Created on: Feb 8, 2017
 *      Author: Thomas Boland
 */

#include <Models/Arena.h>

Arena::Arena() {
	// Arena divided into 3'x3' cells
	// Each cell has tags for [nearest] objects
	// Finer movement should be able to be done
	// after major cell movement

	// 288 252 216 180 144 108 72 36 0

	cells = {"A0" = nullptr,
	         "A1" = nullptr,
	         "A2" = nullptr,
	         "A3" = nullptr,
	         "A4" = nullptr,
	         "A5" = nullptr,
	         "A6" = nullptr,
		     "A7" = nullptr,
			 "A8" = nullptr,
			 "A9" = nullptr,
			 "A10" = nullptr,
			 "A11" = nullptr,
			 "A12" = nullptr,
			 "A13" = nullptr,
			 "A14" = nullptr,
			 "A15" = nullptr,
			 "A16" = nullptr,
			 "B0" = nullptr,
	         "B1" = nullptr,
	         "B2" = nullptr,
	         "B3" = nullptr,
	         "B4" = nullptr,
	         "B5" = nullptr,
	         "B6" = nullptr,
		     "B7" = nullptr,
			 "B8" = nullptr,
			 "B9" = nullptr,
			 "B10" = nullptr,
			 "B11" = nullptr,
			 "B12" = nullptr,
			 "B13" = nullptr,
			 "B14" = nullptr,
			 "B15" = nullptr,
			 "B16" = nullptr,
			 "C0" = nullptr,
	         "C1" = nullptr,
	         "C2" = nullptr,
	         "C3" = nullptr,
	         "C4" = nullptr,
	         "C5" = nullptr,
	         "C6" = nullptr,
		     "C7" = nullptr,
			 "C8" = nullptr,
			 "C9" = nullptr,
			 "C10" = nullptr,
			 "C11" = nullptr,
			 "C12" = nullptr,
			 "C13" = nullptr,
			 "C14" = nullptr,
			 "C15" = nullptr,
			 "C16" = nullptr,
			 "D0" = nullptr,
	         "D1" = nullptr,
	         "D2" = nullptr,
	         "D3" = nullptr,
	         "D4" = nullptr,
	         "D5" = nullptr,
	         "D6" = nullptr,
		     "D7" = nullptr,
			 "D8" = nullptr,
			 "D9" = nullptr,
			 "D10" = nullptr,
			 "D11" = nullptr,
			 "D12" = nullptr,
			 "D13" = nullptr,
			 "D14" = nullptr,
			 "D15" = nullptr,
			 "D16" = nullptr,
			 "E0" = nullptr,
	         "E1" = nullptr,
	         "E2" = nullptr,
	         "E3" = nullptr,
	         "E4" = nullptr,
	         "E5" = nullptr,
	         "E6" = nullptr,
		     "E7" = nullptr,
			 "E8" = nullptr,
			 "E9" = nullptr,
			 "E10" = nullptr,
			 "E11" = nullptr,
			 "E12" = nullptr,
			 "E13" = nullptr,
			 "E14" = nullptr,
			 "E15" = nullptr,
			 "E16" = nullptr,
			 "F0" = nullptr,
	         "F1" = nullptr,
	         "F2" = nullptr,
	         "F3" = nullptr,
	         "F4" = nullptr,
	         "F5" = nullptr,
	         "F6" = nullptr,
		     "F7" = nullptr,
			 "F8" = nullptr,
			 "F9" = nullptr,
			 "F10" = nullptr,
			 "F11" = nullptr,
			 "F12" = nullptr,
			 "F13" = nullptr,
			 "F14" = nullptr,
			 "F15" = nullptr,
			 "F16" = nullptr,
			 "G0" = nullptr,
	         "G1" = nullptr,
	         "G2" = nullptr,
	         "G3" = nullptr,
	         "G4" = nullptr,
	         "G5" = nullptr,
	         "G6" = nullptr,
		     "G7" = nullptr,
			 "G8" = nullptr,
			 "G9" = nullptr,
			 "G10" = nullptr,
			 "G11" = nullptr,
			 "G12" = nullptr,
			 "G13" = nullptr,
			 "G14" = nullptr,
			 "G15" = nullptr,
			 "G16" = nullptr,
			 "H0" = nullptr,
	         "H1" = nullptr,
	         "H2" = nullptr,
	         "H3" = nullptr,
	         "H4" = nullptr,
	         "H5" = nullptr,
	         "H6" = nullptr,
		     "H7" = nullptr,
			 "H8" = nullptr,
			 "H9" = nullptr,
			 "H10" = nullptr,
			 "H11" = nullptr,
			 "H12" = nullptr,
			 "H13" = nullptr,
			 "H14" = nullptr,
			 "H15" = nullptr,
			 "H16" = nullptr,
			 "I0" = nullptr,
	         "I1" = nullptr,
	         "I2" = nullptr,
	         "I3" = nullptr,
	         "I4" = nullptr,
	         "I5" = nullptr,
	         "I6" = nullptr,
		     "I7" = nullptr,
			 "I8" = nullptr,
			 "I9" = nullptr,
			 "I10" = nullptr,
			 "I11" = nullptr,
			 "I12" = nullptr,
			 "I13" = nullptr,
			 "I14" = nullptr,
			 "I15" = nullptr,
			 "I16" = nullptr};
}

